config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get '/signup', to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users
  end
  resources :users
  resources :episodes
  resources :relationships, only: [:create, :destroy]
  post "/tag_relations", to: "tag_relations#create"
  patch "/tag_relations", to: "tag_relations#create"
  get '/episodes', to: 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :episodes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  # source: によってfollowedをfollowingとして扱えるようになる
  has_many :following, through: :active_relationships, source: :followed
  # 「followers」の単数形「follower」で自動的に外部キーfollower_idを探索するため、
  # sourceがなくても良い
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :tag_relations, dependent: :destroy
  # has_many :tag_episodes, through: :tag_relations, source: :episode, dependent: :destroy
  has_many :tags, through: :tag_relations

  has_one_attached :profile_icon
  has_one_attached :strength_image
  validates :profile_icon, :strength_image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                              message: "無効な画像形式です" },
                                size:         { less_than: 5.megabytes,
                                              message:   "ファイルサイズが5MB以上あるため投稿できません" }

  validates :name,  presence: true, length: { maximum: 20 }
  # ほとんどのデータベースでは文字列の上限を255としているため、maximumを設定
  validates :profile, presence: true, uniqueness: true, length: { maximum: 255 }
  validate :check_profile
  #:allow_nilオプションは、対象の値がnilの場合にバリデーションをスキップする
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password
  attr_accessor :remember_token

  def check_profile
    unless self.profile.start_with?("https://libecity.com/user_profile/")
      errors.add(:base, "そのプロフィールURLは使用できません")
    end
  end

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # セッションハイジャック防止のためにセッショントークンを返す
  # この記憶ダイジェストを再利用しているのは単に利便性のため
  # remember_digest が nil の場合は remember メソッドを実行する
  def session_token
    remember_digest || remember
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    # remember_digestの暗号化された文字列が
    # 検証したい値(remember_token)から暗号化する文字列と一致するかを検証
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # フォローされているユーザーか、現在のユーザーに対応するuser_idを持つ
  # エピソードを返す
  def feed
    part_of_feed = "relationships.follower_id = :id or episodes.user_id = :id"
    Episode.left_outer_joins(user: :followers)
            .where(part_of_feed, { id: id }).distinct
            .includes(:user, image_attachment: :blob)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user unless self == other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    following.delete(other_user)
  end

  # 現在のユーザーが他のユーザーをフォローしていればtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :show, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :set_q, only: [:index]

  def index
    @users = @q.result.page(params[:page]).per(12)
    if @users.blank?
      flash.now[:success] = "該当のユーザーは見つかりませんでした。"
    end
  end

  def show
    @user = User.find(params[:id])
    @episodes = @user.episodes.page(params[:page]).per(12)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.profile_icon.attach(params[:user][:profile_icon]) if @user.profile_icon.attached?
    @user.strength_image.attach(params[:user][:strength_image]) if @user.strength_image.attached?
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "ユーザー登録に成功しました"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url, status: :see_other
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(12)
    render 'show_follow', status: :unprocessable_entity
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(12)
    render 'show_follow', status: :unprocessable_entity
  end

  private

    def set_q
      @q = User.ransack(params[:q])
    end

    def user_params
      # adminを含んでいないのは任意のユーザーが
      # 自分自身にアプリケーションの管理者権限を与えることを防止するため
      params.require(:user).permit(:name, :profile, :password,
                                  :password_confirmation, :profile_icon, :strength_image)
    end

    # beforeフィルタ

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  # このメソッドは必要ないが一応書いておく
  # def gravatar_for(user, options = { size: 80 })
  #   size         = options[:size]
  #   gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-outline btn-primary justify-end" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-8 mx-auto">
    <div class="flex flex-col text-center w-full mb-8">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900"><%= yield(:form_title) %></h1>
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2 justify-center">
        <%= form_with(model: @user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">リベ名</label>
              <%= f.text_field :name, class:"input input-bordered input-info w-full bg-white" %>
            </div>
          </div>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">プロフィールURL</label>
              <%= f.text_field :profile, class:"input input-bordered input-info w-full bg-white" %>
            </div>
          </div>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">パスワード(6文字以上)</label>
              <%= f.password_field :password, class:"input input-bordered input-info w-full bg-white" %>
            </div>
          </div>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">確認用</label>
              <%= f.password_field :password_confirmation, class:"input input-bordered input-info w-full bg-white" %>
            </div>
          </div>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">プロフィールアイコン</label>
              <%= f.file_field :profile_icon, accept: "image/jpeg,image/gif,image/png", class:"file-input file-input-bordered file-input-primary w-full" %>
            </div>
          </div>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">資質一覧の写真</label>
              <%= f.file_field :strength_image, accept: "image/jpeg,image/gif,image/png", class:"file-input file-input-bordered file-input-primary w-full" %>
            </div>
          </div>
          <div class="flex justify-around p-4 w-full">
          <% if logged_in? %>
            <%= f.submit yield(:button_text), class: "btn btn-primary flex mx-auto py-2 px-8 text-lg" %>
          <% else %>
            <%= link_to "ログイン画面へ", login_path, class: "btn  btn-outline btn-primary flex mx-4 py-2 px-8 text-lg" %>
            <%= f.submit yield(:button_text), class: "btn btn-primary flex mx-8 py-2 px-8 text-lg" %>
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed: @user),
              html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<% if current_page?(users_path) %>
  <div class="md:w-1/2 xl:w-1/4 p-4">
<% else %>
  <div class="md:w-1/2 xl:w-1/2 p-4">
<% end %>
    <div class="card card-side bg-base-100 shadow-xl">
      <figure class="w-1/3">
        <% if user.profile_icon.attached? %>
          <%= link_to user_path(user) do %>
            <%= image_tag user.profile_icon %>
          <% end %>
        <% else %>
          <%= link_to user_path(user) do %>
            <%= image_tag("no_image.jpg", alt: "no_image") %>
          <% end %>
        <% end %>
      </figure>
      <div class="card-body">
        <h2 class="card-title link link-hover"><%= link_to user.name, user %></h2>
        <div class="card-actions justify-end">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, data: { "turbo-method": :delete,
                                                              turbo_confirm: "本当に削除しますか？" }, class:"btn btn-outline btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザー編集') %>
<% provide(:button_text, '保存') %>
<% provide(:form_title, 'プロフィール編集') %>
<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<section class="text-gray-600">
  <div class="container p-8 mx-auto">
    <div class="md:flex md:flex-wrap w-full mb-20">
      <div class="md:w-1/2 w-full mb-6 md:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">ユーザー一覧</h1>
      </div>
      <div class="md:w-1/2 mb-6 md:mb-0">
        <%= search_form_for @q do |f| %>
        <div class="form-control">
          <div class="">
            <%= f.search_field :name_cont, placeholder: "検索キーワードを入力", class:"input input-bordered input-primary w-full mb-4" %>
          </div>
          <div class="flex">
            <%= f.submit '検索', class:"btn btn-primary btn-square  w-1/2 lg:w-2/12 my-4" %>
            <%= link_to "リセット", users_path, class: "btn btn-outline btn-primary btn-square w-1/2 lg:w-2/12 my-4 mx-8" %>
          </div>          
        </div>
        <% end %>
      </div>
    </div>
    <div class="relative">
      <div id="users" class="absolute w-full">
        <%# 今のページの`<turbo-frame>` %>
        <%= turbo_frame_tag "users-page-#{@users.current_page}" do %>
        <%# 今のページで取得したユーザー一覧 %>
        <div class="flex flex-wrap -m-4 my-4">
          <%= render @users %>
        </div>
        <%# 遅延読み込みで次ページを取得する`<turbo-frame>` %>
        <%= turbo_frame_tag "users-page-#{@users.next_page}", loading: :lazy, src: path_to_next_page(@users) %>
        <% end %>
      </div>
      <div class="absolute">
        <%= render 'shared/back_button' %>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<% provide(:button_text, '新規登録') %>
<% provide(:form_title, '新規登録') %>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto flex flex-wrap">
    <div class="flex flex-wrap w-full">
      <div class="lg:w-1/2 px-4 mb-8">
        <div class="flex flex-wrap w-full">
          <div class="flex w-2/3 px-4">
            <div class="avatar">
              <div class="w-24 rounded-full">
                <% if @user.profile_icon.attached? %>
                  <%= image_tag @user.profile_icon %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
            <p class="text-2xl font-bold px-4 py-8"><%= @user.name %></p>
          </div>
          <div class="w-1/3 py-8">
            <%= link_to "#{@user.profile}", target: :_blank, rel: "noopener noreferrer" do  %>
              <p class="btn btn-outline justify-end">リベシティのプロフィール</p>
            <% end %>
          </div>
        </div>
        <div class="flex flex-wrap w-full justify-center">
          <%= render 'shared/stats' %>
        </div>
        <div class="card card-side bg-base-100 shadow-xl">
          <div class="card-body">
            <div class="flex justify-center">
              <div class="object-contain">
                <% if @user.strength_image.attached? %>
                  <%= image_tag @user.strength_image %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="lg:w-1/2 w-full px-4">
        <div class="flex flex-wrap mb-8">
          <p class="text-xl text-gray-400 font-semibold link link-hover"><%= link_to "フォロワー中", following_user_path(@user) %></p>
          <p class="text-xl text-gray-400 font-semibold link link-hover mx-auto"><%= link_to "フォロワー", followers_user_path(@user) %></p>
          <p class="text-xl font-semibold">エピソード一覧</p>
        </div>
        <% if @episodes.any? %>
          <div class="relative">
            <div id="episodes" class="absolute w-full">
              <%# 今のページの`<turbo-frame>` %>
              <%= turbo_frame_tag "episodes-page-#{@episodes.current_page}" do %>
                <%# 今のページで取得したエピソード一覧 %>
                <div class="flex flex-wrap -m-4 my-4">
                  <%= render @episodes %>
                </div>
                <%# 遅延読み込みで次ページを取得する`<turbo-frame>` %>
                <%= turbo_frame_tag "episodes-page-#{@episodes.next_page}", loading: :lazy, src: path_to_next_page(@episodes) %>
              <% end %>
            </div>
              <div class="absolute">
                <%= render 'shared/back_button' %>
              </div>
          </div>
          <div class="absolute">
            <%= render 'shared/back_button' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto flex flex-wrap">
    <div class="flex flex-wrap w-full">
      <div class="lg:w-1/2 px-4 mb-8">
        <div class="flex flex-wrap w-full">
          <div class="flex w-2/3 px-4">
            <div class="avatar">
              <div class="w-24 rounded-full">
                <% if @user.profile_icon.attached? %>
                  <%= image_tag @user.profile_icon %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
            <p class="text-2xl font-bold px-4 py-8"><%= @user.name %></p>
          </div>
          <div class="w-1/3 py-8">
            <%= link_to "#{@user.profile}", target: :_blank, rel: "noopener noreferrer" do  %>
              <p class="btn btn-outline justify-end">リベシティのプロフィール</p>
            <% end %>
          </div>
        </div>
        <div class="flex flex-wrap w-full justify-center">
          <%= render 'shared/stats' %>
        </div>
        <div class="card card-side bg-base-100 shadow-xl">
          <div class="card-body">
            <div class="flex justify-center">
              <div class="object-contain">
                <% if @user.strength_image.attached? %>
                  <%= image_tag @user.strength_image %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="lg:w-1/2 w-full px-4">
        <div class="flex flex-wrap mb-8">
          <% if @title == "フォロー中" %>
            <p class="text-xl font-semibold"><%= @title %></p>
            <p class="text-xl text-gray-400 font-semibold mx-auto link link-hover"><%= link_to "フォロワー", followers_user_path(@user) %></p>
          <% else %>
            <p class="text-xl text-gray-400 font-semibold link link-hover"><%= link_to "フォロー中", following_user_path(@user) %></p>
            <p class="text-xl font-semibold mx-auto"><%= @title %></p>
          <% end %>
          <p class="text-xl text-gray-400 font-semibold link link-hover"><%= link_to "エピソード一覧", user_path(@user) %></p>
        </div>
        <div class="relative">
          <div id="users" class="absolute">
            <%# 今のページの`<turbo-frame>` %>
            <%= turbo_frame_tag "users-page-#{@users.current_page}" do %>
            <%# 今のページで取得したユーザー一覧 %>
            <div class="flex flex-wrap -m-4 my-4">
              <%= render @users %>
            </div>
            <%# 遅延読み込みで次ページを取得する`<turbo-frame>` %>
            <%= turbo_frame_tag "users-page-#{@users.next_page}", loading: :lazy, src: path_to_next_page(@users) %>
            <% end %>
          </div>
          <div class="absolute">
            <%= render 'shared/back_button' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>