config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get '/signup', to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users
  end
  resources :users
  resources :episodes
  resources :relationships, only: [:create, :destroy]
  post "/tag_relations", to: "tag_relations#create"
  patch "/tag_relations", to: "tag_relations#create"
  get '/episodes', to: 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :episodes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  # source: によってfollowedをfollowingとして扱えるようになる
  has_many :following, through: :active_relationships, source: :followed
  # 「followers」の単数形「follower」で自動的に外部キーfollower_idを探索するため、
  # sourceがなくても良い
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :tag_relations, dependent: :destroy
  # has_many :tag_episodes, through: :tag_relations, source: :episode, dependent: :destroy
  has_many :tags, through: :tag_relations

  has_one_attached :profile_icon
  has_one_attached :strength_image
  validates :profile_icon, :strength_image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                              message: "無効な画像形式です" },
                                size:         { less_than: 5.megabytes,
                                              message:   "ファイルサイズが5MB以上あるため投稿できません" }

  validates :name,  presence: true, length: { maximum: 20 }
  # ほとんどのデータベースでは文字列の上限を255としているため、maximumを設定
  validates :profile, presence: true, uniqueness: true, length: { maximum: 255 }
  validate :check_profile
  #:allow_nilオプションは、対象の値がnilの場合にバリデーションをスキップする
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password
  attr_accessor :remember_token

  def check_profile
    unless self.profile.start_with?("https://libecity.com/user_profile/")
      errors.add(:base, "そのプロフィールURLは使用できません")
    end
  end

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # セッションハイジャック防止のためにセッショントークンを返す
  # この記憶ダイジェストを再利用しているのは単に利便性のため
  # remember_digest が nil の場合は remember メソッドを実行する
  def session_token
    remember_digest || remember
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    # remember_digestの暗号化された文字列が
    # 検証したい値(remember_token)から暗号化する文字列と一致するかを検証
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # フォローされているユーザーか、現在のユーザーに対応するuser_idを持つ
  # エピソードを返す
  def feed
    part_of_feed = "relationships.follower_id = :id or episodes.user_id = :id"
    Episode.left_outer_joins(user: :followers)
            .where(part_of_feed, { id: id }).distinct
            .includes(:user, image_attachment: :blob)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user unless self == other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    following.delete(other_user)
  end

  # 現在のユーザーが他のユーザーをフォローしていればtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/views/shared/_back_button.html.erb
<div class="fixed bottom-8 right-8 btn btn-outline" onclick="scrollToTop()">Topに戻る</div>

<script>
  function scrollToTop() {
    scrollTo(0, 0);
  }
</script>

app/views/shared/_episode_form.html.erb
<%= form_with(model: @episode) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "タイトルを入力" %>
  </div>  

  <div class="field">
    <%= f.text_area :content, placeholder: "エピソードを入力" %>
  </div>

  <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <%= tag.label do %>
        <%= tag.check_box class:"btn-check", id:"btn-check#{ tag }", autocomplete:"off" %>
        <label class="btn btn-primary" for="btn-check<%= tag %>">
          <%= tag.text %>
        </label>
      <% end %>
    <% end %>
  </div>

  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error shadow-lg">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="episodes">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: { controller: :static_pages, action: :home } %> 
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class=px-4 py-8">
  <% unless @user == current_user %>
    <%= render 'follow_form' if logged_in? %>
  <% end %>
</div>
<div class="stats">
  <a href="<%= following_user_path(@user) %>" class="flex link link-info">
    <strong id="following" class="stat w-1/3">
      <%= @user.following.count %>
    </strong>
    <p class="w-2/3 py-4">フォロー</p>
  </a>
  <a href="<%= followers_user_path(@user) %>" class="flex link link-info">
    <strong id="followers" class="stat w-1/3">
      <%= @user.followers.count %>
    </strong>
    <p class="w-2/3 py-4">フォロワー</p>
  </a>
</div>