config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get '/signup', to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users
  end
  resources :users
  resources :episodes
  resources :relationships, only: [:create, :destroy]
  post "/tag_relations", to: "tag_relations#create"
  patch "/tag_relations", to: "tag_relations#create"
  get '/episodes', to: 'static_pages#home'
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :user

  has_many :tag_relations, dependent: :destroy
  # has_many :tag_users, through: :tag_relations, source: :user, dependent: :destroy
  has_many :tags, through: :tag_relations

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  # 文字制限は変更の予定
  validates :content, presence: true, length: { maximum: 1000 }
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :set_q, only: [:index]

  def index
    @episodes = @q.result.page(params[:page]).per(12)
    @episode  = current_user.episodes.build
    @tags = Tag.all.order(:id)
    if @episodes.blank?
      flash.now[:success] = "該当のエピソードは見つかりませんでした。"
    end
  end

  def new
    @episode = Episode.new
    @tags = Tag.all.order(:id)
  end

  def create
    @episode = current_user.episodes.build(episode_params)
    @tag_ids = params[:episode][:tag_ids]
    unless @tag_ids.nil?
      if @tag_ids.count > 2
        @tags = Tag.all.order(:id)
        flash[:danger] = "選択できる資質は2つまでです"
        render 'new', status: :unprocessable_entity and return
      end
      # 空文字を除いてeach文を回している
      @tag_ids.reject { |id| id.blank? }.each do |tag_id|
        @tag_relation = @episode.tag_relations.build(tag_id: tag_id, user_id: current_user.id)
      end
    end
    if @episode.save
      flash[:success] = "エピソードを投稿しました"
      redirect_to episodes_path
    else
      @tags = Tag.all.order(:id)
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @episode.update(episode_params)
      flash[:success] = "エピソードの内容を更新しました"
      redirect_to @episode
    else
      render 'edit', status: :unprocessable_entity
    end  
  end

  def show
    @episode = Episode.find(params[:id])
    @tags = Tag.all.order(:id)
    @tag_relation = current_user.tag_relations.find_or_initialize_by(episode_id: @episode.id)
    @current_user_select_tags = current_user.tag_relations.where(episode_id: @episode.id).pluck(:tag_id)
    @episode_tags = @episode.tags.group(:name).count.sort_by { |name, count| [-count, name] }
  end

  def destroy
    @episode.destroy
    flash[:success] = "投稿を削除しました"
    # 直前のページにリダイレクトしなければ指定したページ(root_url)へリダイレクト
    redirect_back_or_to(root_url, status: :see_other)
  end

  private

    def set_q
      @q = Episode.ransack(params[:q])
    end

    def episode_params
      params.require(:episode).permit(:title, :content)
    end

    def tag_params
      params.require(:episode).permit(tag_ids: [])
    end

    def correct_user
      @episode = current_user.episodes.find_by(id: params[:id])
      redirect_to root_url, status: :see_other if @episode.nil?
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  # 改行を反映させるためメソッド
  # http://taustation.com/rails-reflecting-newline-code/
  def html_safe_newline(str)
    safe_join(str.split(/\n|\r|\r\n/), tag.br).html_safe
  end

  def episode_tags_info(episode)
    # 選択されたタグの多い順、同数の場合はタグ名で昇順にしている
    tag_counts = episode.tags.group(:name).count.sort_by { |name, count| [-count, name] }
    tag_name, tag_count = tag_counts.first
    {
      tag_name: tag_name,
      tag_count: tag_count,
      other_tag_count: tag_counts.size - 1
    }
  end
    
end

app/views/episodes/_episode.html.erb
<div class="<%= current_page?(episodes_path) ? 'md:w-1/2 xl:w-1/4' : 'md:w-1/2 xl:w-1/2' %> p-4">
    <div class="card card-side bg-base-100 shadow-xl">
      <div class="card-body">
        <div class="flex flex-wrap">
          <div class="w-1/3">
            <div class="avatar">
              <div class="w-12 rounded-full">
                <% if episode.user.profile_icon.attached? %>
                  <%= image_tag episode.user.profile_icon %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="w-2/3">
            <h2 class="card-title link link-hover"><%= link_to "#{episode.title}", episode_path(episode) %></h2>
          </div>
        </div>
        <div class="flex flex-wrap">
          <p><%=  episode.content.truncate(50) %></p>
        </div>
        <% unless episode.tags.empty? %>
          <% tag_info = episode_tags_info(episode) %>
          <div class="flex flex-wrap">
            <button class="badge badge-md badge-primary gap-2 ml-4 my-4">
              <%= tag_info[:tag_name] %>
              <div class="badge badge-ghost badge-xs"><%= tag_info[:tag_count] %></div>
            </button>
            <% if tag_info[:other_tag_count] > 0 %>
              <p class="ml-2 my-auto">+<%= tag_info[:other_tag_count] %></p>
            <% end %>
          </div>
        <% end %>
        <div class="card-actions justify-end">
          <div class="flex">
            <%= link_to "詳細ページへ", episode_path(episode), class:"btn btn-outline btn-primary" %>
            <% if current_user.admin? || current_user?(episode.user) %>
              <%= link_to "削除", episode, data: { "turbo-method": :delete,turbo_confirm: "投稿を削除します" }, class:"btn btn-outline btn-primary ml-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/episodes/edit.html.erb
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-8 mx-auto">
    <div class="flex flex-col text-center w-full mb-8">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">エピソード編集</h1>
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="w-full">
        <%= form_with(model: @episode) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="p-2">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">タイトル</label>
              <%= f.text_field :title, class:"input input-bordered input-info w-full bg-white", placeholder: "タイトルを入力" %>
            </div>
          </div>
          <div class="p-2">
            <div class="relative">
              <label for="message" class="leading-7 text-base text-gray-600">内容</label>
              <%= f.text_area :content, class:"textarea textarea-bordered textarea-lg textarea-info w-full bg-white",placeholder: "エピソードを入力" %>
          </div>
          <div class="p-2 w-full">
            <%= f.submit "編集", class: "btn btn-primary flex mx-auto py-2 px-8 text-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/episodes/index.html.erb
<% provide(:title, 'All Episodes') %>
<section class="text-gray-600">
  <div class="container p-8 mx-auto">
    <div class="flex flex-wrap w-full mb-20">
      <div class="md:w-1/2 w-full mb-6 md:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">エピソード一覧</h1>
      </div>
      <div class="md:w-1/2 mb-6 md:mb-0">
        <%= search_form_for @q do |f| %>
          <div class="form-control">
            <div class="">
              <%= f.search_field :title_or_content_cont, placeholder: "検索キーワードを入力", class:"input input-bordered input-primary w-full mb-4" %>
            </div>
            <div tabindex="0" class="collapse collapse-arrow border border-base-300 bg-base-100 rounded-box">
              <input type="checkbox" /> 
              <div class="collapse-title text-xl font-medium">
                資質で検索する
              </div>
              <div class="collapse-content"> 
                <%= f.collection_check_boxes :tags_id_in, @tags, :id, :name, {include_hidden: false} do |tag| %>
                  <%= render 'tags/containing_element', tag: tag %>
                  <%= tag.label do %>
                    <%= tag.check_box %>
                    <%= tag.text %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="flex">
              <%= f.submit '検索', class:"btn btn-primary btn-square  w-1/2 lg:w-2/12 my-4" %>
              <%= link_to "リセット", episodes_path, class: "btn btn-outline btn-primary btn-square w-1/2 lg:w-2/12 my-4 mx-8" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="relative">
      <div id="episodes" class="absolute w-full">
        <%# 今のページの`<turbo-frame>` %>
        <%= turbo_frame_tag "episodes-page-#{@episodes.current_page}" do %>
        <%# 今のページで取得したエピソード一覧 %>
        <div class="md:flex md:flex-wrap -m-4 my-4">
          <%= render @episodes %>
        </div>
        <%# 遅延読み込みで次ページを取得する`<turbo-frame>` %>
        <%= turbo_frame_tag "episodes-page-#{@episodes.next_page}", loading: :lazy, src: path_to_next_page(@episodes) %>
        <% end %>
      </div>
      <div class="absolute">
        <%= render 'shared/back_button' %>
      </div>
    </div>
  </div>
</section>

app/views/episodes/new.html.erb
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-8 mx-auto">
    <div class="flex flex-col text-center w-full mb-8">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">新規投稿</h1>
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2">
        <%= form_with(model: @episode) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="p-2 w-full">
            <div class="relative">
              <label class="leading-7 text-base text-gray-600">タイトル</label>
              <%= f.text_field :title, class:"input input-bordered input-info w-full bg-white", placeholder: "タイトルを入力" %>
            </div>
          </div>
          <div class="p-2 w-full">
            <div class="relative">
              <label for="message" class="leading-7 text-base text-gray-600">内容</label>
              <%= f.text_area :content, class:"textarea textarea-bordered textarea-lg textarea-info w-full bg-white",placeholder: "エピソードを入力" %>
          </div>
          <div tabindex="0" class="collapse collapse-arrow border border-base-300 bg-white rounded-box my-4">
            <input type="checkbox" /> 
            <div class="collapse-title text-xl font-medium">
              資質を選択する (2つまで)
            </div>
            <div class="collapse-content"> 
              <%= f.collection_check_boxes(:tag_ids, @tags, :id, :name, { include_hidden: false }) do |tag| %>
                <%= render 'tags/containing_element', tag: tag %>
                <%= tag.check_box %>
                <%= tag.text %>
              <% end %>
            </div>
          </div>  
          <div class="p-2 w-full">
            <%= f.submit "投稿", class: "btn btn-primary flex mx-auto py-2 px-8 text-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/episodes/show.html.erb
<% provide(:title, 'エピソード') %>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto flex flex-wrap">
    <div class="flex flex-wrap w-full">
      <div class="lg:w-1/2 px-4 mb-8">
        <div class="flex flex-wrap w-full">
          <div class="flex w-2/3 px-4">
            <div class="avatar">
              <div class="w-24 rounded-full">
                <% if @episode.user.profile_icon.attached? %>
                  <%= image_tag @episode.user.profile_icon %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
            <%= link_to @episode.user.name, user_path(@episode.user.id), class:"text-2xl font-bold px-4 py-8 link link-hover" %>
          </div>
          <div class="w-1/3 py-8">
            <%= link_to "#{@episode.user.profile}", target: :_blank, rel: "noopener noreferrer" do  %>
              <p class="btn btn-outline justify-end">リベシティのプロフィール</p>
            <% end %>
          </div>
          <%
=begin%>
<div class="w-1/3 px-4 py-8">
            <% unless @episode.user == current_user %>
              <%= render 'users/follow_form', user: @episode.user %>
            <% end %>
          </div> 
<%
=end%>
        </div>
        <%
=begin%>
<div class="flex flex-wrap w-full justify-center">
          <%= render 'shared/stats' %>
        </div> 
<%
=end%>
        <div class="card card-side bg-base-100 shadow-xl">
          <div class="card-body">
            <div class="flex flex-wrap">
              <p class="card-title text-lg md:text-xl my-8">資質一覧</p>
            </div>
            <div class="flex justify-center">
              <div class="object-contain">
                <% if @episode.user.strength_image.attached? %>
                  <%= image_tag @episode.user.strength_image %>
                <% else %>
                  <%= image_tag("no_image.jpg", alt: "no_image") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="lg:w-1/2 w-full px-4">
        <div class="card card-side bg-base-100 shadow-xl">
          <div class="card-body">
            <div class="flex flex-wrap">
              <p class="card-title text-2xl my-8"><%= @episode.title %></p>
            </div>
            <div class="flex flex-wrap">
              <p class="card-title text-lg my-8"><%= html_safe_newline(@episode.content) %></p>
            </div>
            <div class="flex flex-wrap">
              <% @episode_tags.map do |tag_name, tag_count| [tag_name, tag_count] %>
                <button class="badge badge-md badge-primary gap-2 ml-4 mb-4">
                  <%= tag_name %>
                  <div class="badge badge-ghost badge-xs"><%= tag_count %></div>
                </button>
              <% end %>
            </div>

            <div tabindex="0" class="collapse collapse-arrow border border-base-300 bg-base-100 rounded-box">
              <input type="checkbox" /> 
              <div class="collapse-title text-xl font-medium">
                資質を選択する (2つまで)
              </div>
              <div class="collapse-content"> 
                <%= form_with model: @tag_relation, url: tag_relations_path do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                  <%= f.hidden_field :episode_id, value: @episode.id %>
                    <%= f.collection_check_boxes(:tag_id, @tags, :id, :name, {checked: @current_user_select_tags, include_hidden: false}) do |tag| %>
                      <%= render 'tags/containing_element', tag: tag %>
                      <%= tag.check_box %>
                      <%= tag.text %>
                    <% end %>
                  <div class="flex w-full">
                    <%= f.submit "資質を選択する", class:"btn btn-sm btn btn-outline btn-primary mt-4" %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="flex w-full mt-4">
              <% if current_user?(@episode.user) %>
                <%= link_to "投稿内容を編集する", edit_episode_path(@episode), class:"btn btn-primary ml-4" %>
                <%= link_to "削除", @episode, data: { "turbo-method": :delete,turbo_confirm: "投稿を削除します" }, class:"btn btn-outline btn-primary ml-4" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>