config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get '/signup', to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users
  end
  resources :users
  resources :episodes
  resources :relationships, only: [:create, :destroy]
  post "/tag_relations", to: "tag_relations#create"
  patch "/tag_relations", to: "tag_relations#create"
  get '/episodes', to: 'static_pages#home'
end

app/views/layouts/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <% if logged_in? %>
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li><%= link_to "ユーザー 一覧", users_path %></li>
          <li><%= link_to "エピソード一覧", episodes_path %></li>
          <li><%= link_to "新規投稿", new_episode_path %></li>
      </div>
    <% end %>
    <%= link_to "StrengthsApp", root_path, class:"btn btn-ghost normal-case text-xl"  %>
  </div>
  <% if logged_in? %>
    <div class="navbar-start hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li><%= link_to "ユーザー一覧", users_path %></li>
        <li><%= link_to "エピソード一覧", episodes_path %></li>
        <li><%= link_to "新規投稿", new_episode_path %></li>
      </ul>
    </div>
    <div class="navbar-end">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <% if current_user.profile_icon.attached? %>
              <%= image_tag current_user.profile_icon %>
            <% else %>
              <%= image_tag("no_image.jpg", alt: "no_image") %>
            <% end %>
          </div>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li><%= link_to "プロフィール詳細", user_path(current_user) %></li>
          <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
          <li><%= link_to "ログアウト", logout_path, data: { "turbo-method": :delete } %></li>
        </ul>
      </div>
    </div>
    </div>
  <% else %>
    <div class="navbar-end">
      <ul class="menu menu-horizontal px-1">
        <li><%= link_to "新規登録", signup_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type} shadow-lg") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>